### ISSUE TITLE
Home page grids are not aligned properly

### ISSUE THREAD

**Issue by avirupchatterjee** [felixdorner/kouki#1]
Home pages Grids after fast row getting moved sidewise. Refer attached screenshot.
<img width="1142" alt="screenshot 2015-10-26 00 46 45" src="https://cloud.githubusercontent.com/assets/8520204/10717757/35140e0c-7b7b-11e5-886b-6bd99f2a32ca.png">
<img width="1172" alt="screenshot 2015-10-26 00 47 04" src="https://cloud.githubusercontent.com/assets/8520204/10717758/3562d7e4-7b7b-11e5-89c7-f050fad1146f.png">

**Comment by avirupchatterjee** [comment]
Please look at the blog logo. The photos are stretching towards left and right.

**Comment by felixdorner** [comment]
Please explain in more depth. As you see in my live demo things are working fine. This is probably a non theme related issue.

**Comment by avirupchatterjee** [comment]
You are right. I have attached another screenshot to describe the issue. In the grid, few rows are actually overlapping outside (Refer the red line). The feature image and the content are aligned to the left. 

Might not be the issue with the theme, but I loved the theme so much do not want to try out anything else. Great work buddy with the theme.

Let me know if you have any input regarding this or else you can close this issue. :)

**Comment by felixdorner** [comment]
Thanks for your description: You are right the layout looks broken on your site. Unfortunately I cannot reproduce the issue which limits my support to some guess-work:

1. Did you tried to check if all the scripts are loading correctly within your local environment? 
2. Did you de-activated all of your plugins to check if this might be caused by a plugin?
3. Did you check the content and title of the 3rd post in the text mode (not visual mode). Sometimes some hidden html elements got copy/pasted accidentially.
