### ISSUE TITLE
W3C Validation

### ISSUE THREAD

**Issue by fredroo** [felixdorner/kouki#4]
please for news versions validate theme with W3C HTML5 tool

**Comment by felixdorner** [comment]
@fredroo first of all hello... 

here is the result of the validation (2 infos & 3 warnings)
https://validator.w3.org/nu/?doc=http%3A%2F%2Fkouki.felixdorner.de%2F

the theme is based on _underscores (http://underscores.me/). since the theme is a little bit older I wasn't sure about the 3 semantic warnings as they also occur within the _underscores starter theme itself. 

As _underscores is maintained by a whole group of contributers who doesn't seem to care about these 3 validation warnings (not errors) I wasn't so sure to care about them either.

I will consider to fix them in a next release.

**Comment by fredroo** [comment]
ok thanks

**Comment by felixdorner** [comment]
Hey @fredroo, I updated the theme and committed the changes to WordPress. It will take some time to get approved. In the meantime you could use the version from here.

**Comment by fredroo** [comment]
thanks a lot
